### ISSUE TITLE
Event Log: filter committed and uncommitted actions

### ISSUE THREAD

**Issue by lcb931023** [AI-Safety-Camp-Tabletop-RPG/companion-app#20]
Viewing options. Be able to hide crossed out actions, and to hide uncommitted actions - effectively only showing the ones that are finalized.

We can reuse the UI for filtering GM NPC notes here.

**Comment by lcb931023** [comment]
I'm seeing a bug where if the user leaves the event log tab and then comes back, none of the events will be displayed.

**Comment by smartdev322** [comment]
I fixed it already and I'll push it with next task.

**Comment by lcb931023** [comment]
![Screen Recording 2023-02-08 at 8 46 55 PM](https://user-images.githubusercontent.com/3478059/217535599-01ed578a-9e08-46e5-859b-d5b5cd6a0f77.gif)
@smartdev322 see above for remaining issue with the filter. Looks like a reactivity problem.
