### ISSUE TITLE
GM Panel: Add free note section

### ISSUE THREAD

**Issue by lcb931023** [AI-Safety-Camp-Tabletop-RPG/companion-app#9]
The GM panel should allow the GM to write down arbitrary notes.

We could reuse the UI in Info section.

**Comment by jandornig** [comment]
started work on this - first version here: https://www.figma.com/file/BHLkTTiKO5iELu5Ww3o3LJ/The-Treacherous-Turn?node-id=5307%3A455&t=i6XJPVLgKd4o0YhP-4
